### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by Pl0414141** [EasyAI/binance_api#1]
Hi,

using ur tool https://github.com/EasyAI/Simple-Binance-Trader will produce the following error in binance_api :

2020-12-10 22:30:38,746:root:update: True, type: SIGNAL, status: {'S': None, 'B': 'PLACED'}
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/root/xxx/v1/core/trader.py", line 246, in _main
    books_data = self.depth_endpoint(sock_symbol)
  File "/root/xxx/v1/binance_api/socket_master.py", line 85, in get_live_depths
    ask_Price_List = self._orderbook_sorter_algo(copy.deepcopy(self.book_data[key]['a']), 'ask')
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 242, in _deepcopy_dict
    for key, value in x.items():
RuntimeError: dictionary changed size during iteration

2020-12-10 22:30:42,047:root:quantity: 8.162372

How to reproduce:

Insert four (4) or more pairs in "TRADING_MARKETS" parameter under "settings" file and start the server (python3 run.py)

**Comment by EasyAI** [comment]
I have fixed this I believe with the new version
